DateTime.js
The `onChange` handler wasn't being triggered when in date-only operation and you clicked on a date in the calendar. It was getting triggered by typing though. This is because `updateDate` wasn't calling `onChange` like `setTime` is. Making them match fixes this issue.
=> updateDate wasn't calling onChange like setTime was

DateTime.js, README.md
The new `onBlur` event is documented. It also has the same semantics as the `onChange` handler: it expects the latest value, rather than the event object.
This is intended to enable not needing to have more heavy-weight save events on every change, but rather saving it for when a user is done providing input.
=> Added a simulation of onBlur to enable final save events and the like

package.json
I was having trouble building with webpack due to an underlying [issue with react-onclickoutside that has since been fixed](https://github.com/Pomax/react-onclickoutside/issues/20). Using the newer 0.3.0, everything is in order.
=> Upgrade react-onclickoutside version to 0.3.0

DateTime.js, README.md, tests/datetime-spec.js
Hey, I'm using your component and would like to be able to use Moment's strict parsing, so if a user types input like
```
2015-10-12xyz
```
Moment detects this as invalid, or in the case of this component, it returns the string `2015-10-12xyz` in the onChange handler rather than a Moment object. Without strict parsing, the parser is a lot more lenient and will happily return a moment representing `2015-10-12` for this input.
This PR adds the functionality as a toggleable prop. Let me know what you think.
=> Add a 'strictParsing' prop which uses Moment's strict parsing.

src/DaysView.js
It fixes the bug when it's December and you click in (supposedly) January days and it goes to November.
=> Fix error when new year's days are showing up (December -> January)

src/DaysView.js
We noticed that rdtActive was not getting set at all. That's because isSame is being called incorrectly for Moment v2+.
The equivalent functionality is to pass a moment as the first argument and the string "day" as the second argument:
"When including a second parameter, it will match all units equal or larger. Passing in month will check month and year. Passing in day will check day, month, and year."
http://momentjs.com/docs/#/query/is-same/
=> Fix bug where rdtActive not getting set

src/TimeView.js
When using the timeFormat for the 12 hour clock, 12PM was displayed as 12AM, and 12AM was displayed as 0:00. This pull request fixes that issue. 
```
<DateTime
value={this.props.endTime}
dateFormat={false}
timeFormat="h:mm A"
/>
```
=> Fix 12 hour time clock to display correct 12AM /12PM in the picker.

package.json
Writing tests often requires them to be run multiple times before they pass. It can be a hassle switching focus back and forth between your editor/IDE (to write code) and terminal (to init test task). By running this npm task the mocha instance will watch for changes in files and automatically re-run the test task, saving you time and energy.
It is run like `npm run test:watch`.
=> Add test task with watch option

README.md, package.json
Referencing issue #108.
I decided for a pre-commit over a pre-push, as I think it's better to see your errors while performing your commits instead of a bunch of problems when pushing. 
The pre-commit hook will run the `lint` and the `test` tasks. If any of them fail the commit will not be accepted. You can disable the hook for the current commit by using `--no-verify` on your commit, e.g. `git commit -m 'Commit message' --no-verify`. This should only be used for commits that break any test but is fixed with a later commit in the same push (if that makes sense :) ).
**Be sure to run `npm install` to get the [`pre-commit`](https://github.com/observing/pre-commit) package.**
=> Add pre-commit hook

react-datetime.d.ts
Since I'm getting errors (from webpack):
```
ERROR in .../react-datetime/react-datetime.d.ts
(57,16): error TS7006: Parameter 'e' implicitly has an 'any' type.
ERROR in .../react-datetime/react-datetime.d.ts
(63,16): error TS7006: Parameter 'e' implicitly has an 'any' type.
```
I though I could fix it.
=> Fixing argument type for onBlur on onFocus events

DateTime.js, tests/datetime-spec.js
The component used to accept an invalid moment object which would have `NaN` as value and would display the value in the input element. This commit changes the value to `''` if this type of object is passed to it.
I do not think `NaN` is an acceptable value for the input field, therefore I think we should handle that case and replace it with an empty string. This PR solves [this](https://github.com/YouCanBookMe/react-datetime/issues/140) issue.
=> Fix for invalid moment object as input value

gulpfile.js, package.json, webpack.config.js
By changing the build config a source map file was added, which is useful for debugging. The non-minified file size was decreased by 3.5kB. The source map file should be included in production so people can use it for debugging. This PR solves issue #144.
- - [ ] I have updated the documentation accordingly.
- - [ ] I have updated the TypeScript type definition accordingly.
=> Change build configuration

package.json
Without this option typescript doesn't find the current type definitions automatically.
For more info see the [docs for publishing type definitions](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).
=> Signpost type definition file in package.json

package.json
The npm package includes several non-essential files. Let's trim those down using the `files` field.
```
$ npm pack
$ tar -tf react-datetime-2.6.0.tgz
package/.eslintrc.js
package/.npmignore
package/.travis.yml
package/CHANGELOG.md
package/CONTRIBUTING.md
package/DateTime.js
package/LICENSE
package/PULL_REQUEST_TEMPLATE.md
package/README.md
package/css/react-datetime.css
package/dist/react-datetime.js
package/dist/react-datetime.min.js
package/example/example.js
package/example/index.html
package/example/react-datetime.css
package/gulpfile.js
package/package.json
package/react-datetime.d.ts
package/src/DaysView.js
package/src/MonthsView.js
package/src/TimeView.js
package/src/YearsView.js
package/src/onClickOutside.js
package/tests/datetime-spec.js
package/tests/testdom.js …
```
=> whitelist npm package files

DateTime.js, README.md, react-datetime.d.ts, tests/datetime-spec.js
This change adds a boolean `utc` prop. When set to `true`, it will cause moment to interpret input times as UTC, rather than the user's local timezone.
This PR will help anyone who deals with timestamps primarily in UTC, for example anyone operating in UTC or across multiple timezones.
I build tools to manage a fleet of satellites in low earth orbit, where local time zones don't make any sense. All of our data is stored and queried as UTC. This change will allow my users to query the dataset using its native timezone.
=> Add support for inputting times as UTC

DateTime.js, example/formatChangeExample.js
In case of dateFormat and/or timeFormat prop change, componentWillReceiveProps was updating only the inputFormat state, not updating the inputValue and leaving it in old format. The value would correctly updated to the new format when the user manually changes the selected datetime.
Fixes https://github.com/YouCanBookMe/react-datetime/issues/166
- \- [ ] I have updated the documentation accordingly.
- \- [ ] I have updated the TypeScript type definition accordingly.
Added example/formatChangeExample.js as demo for the format change. To run it simply replace example.js with formatChangeExample.js in example/webpack.config.js. Date format should change after 3 seconds.
=> Fixed the problem with displayed selected datetime not changing when the format props change

example/example.js, src/MonthsView.js, src/YearsView.js, tests/datetime-spec.js
Disable dates according to isValidDate function when the viewMode and dateFormat props are set.
My solution was to add a disabled class when the isValidDate is not satisfied and thus allowing the click accordingly!
This should be fixed #129 
- \- [ ] I have updated the documentation accordingly.
- \- [ ] I have updated the TypeScript type definition accordingly.
=> Disable months and years according to isValidDate

.travis.yml, README.md, package.json, react-datetime.d.ts, typings/index.d.ts, typings/react-datetime-tests.tsx, typings/tsconfig.json
Typescript 2.0 has a new mechanism for resolving types for modules. This PR updates the typings for react-datetime to be compatible with with the latest typescript. It also includes a couple of fixes and enhancements to the typings.
- Restrict `viewMode` to the correct strings (or a number).
- Improve typings for `timeConstraints`
- Fix `renderDay`, `renderMonth`, `renderYear` to the correct return types.
- Improve typings for `inputProps`, limiting it to only those allowed on input elements
- Fix `ReactDatetime` to be a class
Fixes issue #181. Improves compatibility with this package.
- - [X] I have updated the documentation accordingly.
- - [X] I have updated the TypeScript type definition accordingly. :P
=> Update typings for Typescript 2.0

src/TimeView.js, tests/datetime-spec.js
According to the moment.js API using a lower case 'a' in timeFormat
should make it use lower case 'am' and 'pm', and vice versa with higher
case. This commit also adds tests for these two specific cases and
formats the code with consistency in mind.
- - [ ] I have updated the documentation accordingly.
- - [ ] I have updated the TypeScript type definition accordingly.
=> Properly set lower/higher case with timeFormat

src/DaysView.js, src/MonthsView.js, src/YearsView.js, tests/datetime-spec.js
When setting isValidDate and viewMode=month and going from monthView to
yearView and then back the current month was rendered as invalid. This
is now fixed. Plus a bunch of consistency formatting fixes.
This is the fix from PR #198
(https://github.com/YouCanBookMe/react-datetime/pull/198).
=> Bug fix for isValiDate

src/YearsView.js, tests/datetime-spec.js
It was not working properly, not sure what it's for. Oldest commit I can trace it back to is this one: https://github.com/YouCanBookMe/react-datetime/commit/d76f7b08bc6bbc4f8a72327400c1ff0739330459
So it might be a left over for when forking from the original repo. Will keep it in the code base for now.
=> Disable rdtOld for year view

DateTime.js
This logic was lost in a previous commit, hopefully this new check will
be enough to cover all the cases as well as not ruining any others. I
did not manage to write a test for this as it required props I do not
know how to mock to be able to reproduce.
=> Respect closeOnSelect property

package.json
It was added in commit https://github.com/YouCanBookMe/react-datetime/commit/84755ceb54dd6f5fe7682912336b243e4b7dc59b but then remove in this commit https://github.com/YouCanBookMe/react-datetime/commit/752fa8b2aee6385115c86d74e8f641de48982323 for no obvious reason. Apparently it's causing some problems for people (https://github.com/YouCanBookMe/react-datetime/issues/399) so adding it back.
=> Add create-react-class dependency

DateTime.d.ts
The changed props definitions actually accept more than just a JS date
object, and the TS definition should reflect this. Fixes #336.
=> Use correct types for props value & defaultValue

DateTime.js, test/tests.spec.js
The `open` prop has been broken for as long as I've been involved in this project, and this change seems to fix it. Now it actually does what it supposed to, it sets the open/closed state of the datepicker.
It's always scary to change the core logic of the component, but I'm so fed up with seeing this issue being reported so I'm just gonna try this code change and see if it works.
=> Fix open prop

DateTime.js, test/tests.spec.js
Added functionality to do not close calendar when `disableOnClickOutside` is set to true.
This pull request fixes bug #402, adding support for `disableOnClickOutside` documented property.
```
[X] I have added tests covering my changes
[X] All new and existing tests pass
```
=> Added support for "disableOnClickOutside" property.

DateTime.d.ts, DateTime.js, README.md, react-datetime.d.ts, test/tests.spec.js
Implement hooks for onSubtractTime and onAddTime. 
This could be used to dynamically load selectable dates for each month.
```
[x] My changes required the documentation to be updated
[x] I have updated the documentation accordingly
[x] I have updated the TypeScript 1.8 type definitions accordingly
[x] I have updated the TypeScript 2.0+ type definitions accordingly
```
I have ran build but it seems to have updated more than only my changes in the dist folder.
=> Add onSubtractTime and onAddTime hooks

src/TimeView.js, test/__snapshots__/snapshots.spec.js.snap
This PR is met to fix issue reported in https://github.com/YouCanBookMe/react-datetime/issues/525
```
[x] I have added tests covering my changes
[ ] All new and existing tests pass
```
=> Remove onTouchStart attribute when used together with onMouseDown

package-lock.json, package.json, test/snapshots.spec.js, test/tests.spec.js
This PR fix tests after update the package-lock
Me and my friend are still using the v2 of this components, and my friend try to fix react@16.9 warning on this PR (https://github.com/YouCanBookMe/react-datetime/pull/674), but he tests are broken, that is because some dependency had updates that changes a little the assets of tests. So I create this PR to fix the tests first. 
```
[ ] I have not included any built dist files (us maintainers do that prior to a new release)
[ ] All new and existing tests pass
```
=> Fix: tests after update package-lock

src/TimeView.js
Clearing interval before create
Scenario: On time picker arrows - right mouse down, left mouse down, both mouse up
Expecting: Time counter stops to increase
Actual: Time counter increasing even after both mouse up
```
```
=> Fix infinity setState when holding multiple buttons down

src/datetime/DateTime.js
Changed react-onclickoutside package usage - providing ref for ClickOutBase component
Due to updates in react around strict mode, findDOMNode raises warning. Error raises in react-onclickoutside package where refs should be used instead findDOMNode. Package has been updated to 6.9.0 where this issue has been solved (https://github.com/Pomax/react-onclickoutside/issues/315), but react-datetime package needs some changed regarding this.
Fixes issue: #626 
```
[ ] I have updated the TypeScript 1.8 type definitions …
```
=> Fixes findDOMNode deprecated warning in Strict Mode

src/datetime/DaysView.js, src/datetime/MonthsView.js, src/datetime/ViewNavigation.js, src/datetime/YearsView.js
Three files use same navigation structure, so I extracted it to a
component for DRY.
- DRY
- Abstracting out implementation details 
```
```
=> Extract ViewNavigation component

src/datetime/DateTime.js, src/datetime/DaysView.js, src/datetime/MonthsView.js, src/datetime/TimeView.js, src/datetime/YearsView.js
Many methods receive arguments related to object state, which they
can access. This might create confusion and inconsistency about the
source of truth. So I removed unnecessary parameters.
- Simplifying methods
- Use component props and state as the source of truth in components 
```
```
=> Remove unneeded parameters

src/datetime/DateTime.js, src/datetime/DaysView.js, src/datetime/YearsView.js
Moved the default implementation of rendering to default props,
reducing the branching. I couldn't change `renderInput` (custom
implementations get wrapped by a `div`, default one doesn't) and
`renderMonth` (default implementation depends on state) trivially,
so I left them out of this PR's scope.
- Simplifies the code
- Reduces branching
```
```
=> Add default render props

src/datetime/DateTime.js
removed one console.log()
Just noticed a console output which irritated me, I guess it is a leftover debugging statement? If so I thought it's easiest to just remove it myself :)
Great work! Keep it up! :)
=> cleanup: remove a probably forgotten console log

package.json
Travis CI build failed for PR #757 due to breaking changes introduced with npm v7. Here's the part of the log related to this issue. 
```
$ npm install 
214npm ERR! code ERESOLVE
215npm ERR! ERESOLVE unable to resolve dependency tree
216npm ERR! 
217npm ERR! While resolving: react-datetime@3.0.4
218npm ERR! Found: react-dom@16.14.0
219npm ERR! node_modules/react-dom
220npm ERR!   dev react-dom@"^16.5.0" from the root project
221npm ERR! 
222npm ERR! Could not resolve dependency:
223npm ERR! peer react-dom@"^15.4.2" from react-addons-test-utils@15.6.2
224npm ERR! node_modules/react-addons-test-utils
225npm ERR!   dev react-addons-test-utils@">=0.13" from the root project
226npm ERR! 
227npm ERR! Fix the upstream dependency conflict, or retry
228npm ERR! this command with --force, or …
```
=> Fix CI build issues related to npm v7

package.json
Adds react 17 as peerDependency to prevent warnings.
Allows react 17 as peerDependency
fixes #792
fixes #774
react-datetime works with react 17.
Testing against react 17 is blocked by enzyme-adapter-17, which still in development: https://github.com/enzymejs/enzyme/pull/2430
```
[X] I have not included any built dist files (us maintainers do that prior to a new release)
[X] All new and existing tests pass
```
=> Allow react 17 as peerDependency

src/DateTime.js
This PR adjusts the code of the `DateTime` component to call the correct log method. At the moment, this code crashes the component if the `value` prop of the `DateTime` component does not match the expected format. See https://github.com/arqex/react-datetime/issues/801
The `log` method was moved outside the class in https://github.com/arqex/react-datetime/commit/d4450038cd901f1e0f31bcd365448820f60c6f67#diff-cae892f0886b91915576f17fd54c818f7ef44b721a3885d4a742039f1c8cad03L557-R611
Unfortunately, the call this method inside of `setViewDate` was not adjusted. This causes the error described above.
```
[ ] My changes …
```
=> Call correct log method in DateTime component to prevent crash on invalid input

package.json
Allow usage with react 18.
Avoid: "react-datetime@3.1.1 requires a peer of react@^16.5.0 || ^17.0.0 but none is installed"
```
[-] I have added tests covering my changes
[-] My changes required the documentation to be updated
```
=> Allow usage with react 18
