arqex/react-datetime

- DateTime.js
- package.json
* This allows passing in class names for the input form (this allows me to reuse global styles for input fields that I have).
* It replaces using `dataset` with an explicit attribute request, which is compatible with all browsers even if it's slightly less pretty. If you were doing more dynamic dataset access this would be even less pretty, but thankfully you're only using one key, so hopefully you're OK with this.
* It adds another dependency to support `classlist`. The polyfill is pretty tiny, if you'd prefer to keep dependencies down, I can integrate the polyfill directly.
> IE support and custom classNames

- src/DaysView.js
- src/MonthsView.js
- src/TimeView.js
- src/YearsView.js
> Add type="button" to buttons to prevent page submit

- src/DaysView.js
> Updated Days View to allow duplicate Weekdays

- DateTime.js
- README.md
- tests/datetime-spec.js
Hello,
I need an `onFocus` prop, I thought others might need it too. I've added it, with a corresponding test and added it to the documentation.
> Add onFocus prop

- example/example.js
- example/index.html
- example/react-datetime.css
- example/webpack.config.js
- package.json
Added a dev setup. `npm run dev` will allow to easily develop locally.
Cheers,
Edo
> Added dev setup.

- src/TimeView.js
I extended time view widget to switch between am/pm and 24h clock modes basing on time format, as arqex described in his post https://github.com/YouCanBookMe/react-datetime/issues/41#issuecomment-190843119
> Customizing the time picker

- README.md
- css/react-datetime.css
- example/example.js
- example/react-datetime.css
- package.json
So I wasn't able to get all four changes in separate pull requests in a clean way - sorry about that.
About the updated README: I changed the example on CodePen so that the input element now has a black border so it's easier to see it (me and a colleague both thought that the component was broken when we opened the CodePen as we didn't see the white input field at first).
> Update README, build scripts, example and indentation

- css/react-datetime.css
- src/TimeView.js
> Adds AM/PM Arrows to toggle between states

- src/TimeView.js
This should resolve Issue #116.
> Create time constraints object on mount instead of assigning to it

- src/TimeView.js
Attempt two of my pull request, should be easier to merge. Fixed a few issues with the time picker.
> Fix bugs with the time picker (Attempt 2)

- CONTRIBUTING.md
- README.md
This PR adds a CONTRIBUTION.md file which will contain guidelines for making a contribution to this repository. 
The idea with this file is not to enforce rules but to give guidelines. In a perfect world I think everyone contributing should follow these guidelines for a shared way-of-working, but I don't think we should deny PRs because they are not following the guidelines.
I hope these guidelines will have people reflect over their current workflow and think about why they are doing things the way they are, because it's easy to get stuck in a workflow where the focus is on producing code and nothing else. When multiple people are involved in a project it's important to make things understandable for everyone, not just yourself. 
With that said I hope to get some feedback on these …
> Add CONTRIBUTION file

- README.md
- react-datetime.d.ts
This is a typescript typings file with corrected definitions for properties and callbacks on `Datetime` object.
This PR should be merged to avoid Typescript compilation errors that result in using the callbacks with wrong callback parameters.
> Updating typings config to reflect actual callback parameters

- gulpfile.js
- package.json
- webpack.config.js
I'm reverting this commit because it made the minified file bigger than the non-minified (?!?).
> Revert "Change build configuration"

- DateTime.js
fix #162 onFocus() and onBlur triggered on inconsistent state.
> fix #162 onFocus() and onBlur triggered on inconsistent state.

- .travis.yml
Both in different OS's and in different versions of Node.
> Test component in more environments

- DateTime.js
- example/viewModeChangeExample.js
currentView could not be changed if the viewMode prop was updated.
Fix Issue #202 
- - [ ] I have updated the documentation accordingly.
- - [ ] I have updated the TypeScript type definition accordingly.
> Fix Issue #202 - View Not Updating when viewMode Changed

- src/DaysView.js
- src/MonthsView.js
- src/TimeView.js
- src/YearsView.js
I hate these types of commits but consistency is king...
> Adjust formatting for improved syntax consistency

- .travis.yml
- DateTime.js
- tests/datetime.spec.js
> Make component react to UTC or Locale prop updates

- README.md
Tagging two people who has been contributing to the project during the latest year that might be interested.
@layneanderson @andjosh
> Add maintainer wanted ad to README

- DateTime.d.ts
- DateTime.js
- README.md
- react-datetime.d.ts
- test/tests.spec.js
- typings/react-datetime-tests.tsx
This is a copy of PR #302. Since I've been so slow at responding the author (@josefernand) have probably lost interest, which I totally understand. However I think this change is a very nice one that I would like to have in master, so I decided to make commit it by myself.
Maybe there's a way to do this correctly, like change @josefernand's PR and then merge it but I don't know any other way than this way.
For other people: #302 is a perfect example of how a PR should look like. Tested, explained and easy to read and understand code. Thanks a lot @josefernand!
> Add callback on view mode changes

- .eslintrc.js
- DateTime.js
- src/CalendarContainer.js
- src/DaysView.js
- src/MonthsView.js
- src/TimeView.js
- src/YearsView.js
> Consistent indentation

- package.json
See https://github.com/YouCanBookMe/react-datetime/issues/408 for details
> Move @types/react back to devDependencies

- src/TimeView.js
- test/__snapshots__/snapshots.spec.js.snap
I copied the code and the commit message from PR #306. Needed to update the snapshot as well.
> Disable context menu in timepicker's up & down arrow

- src/TimeView.js
Fixes issue #446 
Please see issue #446 for details
```
```
> Fix for AM/PM toggle (fixes #446)

- DateTime.js
- README.md
- react-datetime.d.ts
- test/tests.spec.js
> Add renderInput prop [duplicate]

- DateTime.js
- README.md
- package.json
- test/tests.spec.js
> Pass closeCalendar to renderInput prop

- Makefile
- src/TimeView.js
- test/__snapshots__/snapshots.spec.js.snap
> Touch support

- DateTime.js
Make `viewDate` update when prop changes. Fixes #468.
> Dynamic viewDate
